/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FestivalStatus = IDL.Variant({
  'Active' : IDL.Null,
  'ComingSoon' : IDL.Null,
});
export const Season = IDL.Variant({ 'Winter' : IDL.Null, 'Summer' : IDL.Null });
export const EventType = IDL.Variant({
  'EDM' : IDL.Null,
  'Family' : IDL.Null,
  'Rave' : IDL.Null,
  'ClubHotel' : IDL.Null,
});
export const FestivalInput = IDL.Record({
  'status' : FestivalStatus,
  'country' : IDL.Text,
  'ticketPriceMax' : IDL.Nat,
  'ticketPriceMin' : IDL.Nat,
  'weekends' : IDL.Text,
  'name' : IDL.Text,
  'ticketUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'season' : Season,
  'ageRestriction' : IDL.Text,
  'company' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'estimatedRevenueMax' : IDL.Text,
  'estimatedRevenueMin' : IDL.Text,
  'location' : IDL.Text,
  'lineup' : IDL.Opt(IDL.Text),
  'specialNotes' : IDL.Opt(IDL.Text),
  'eventType' : EventType,
});
export const FestivalId = IDL.Nat;
export const PackageType = IDL.Variant({
  'VIP' : IDL.Null,
  'Weekend1' : IDL.Null,
  'Weekend2' : IDL.Null,
  'FullWeekend' : IDL.Null,
  'Accommodation' : IDL.Null,
  'Transfer' : IDL.Null,
  'FlightPackage' : IDL.Null,
});
export const PackageInput = IDL.Record({
  'packageType' : PackageType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'includes' : IDL.Vec(IDL.Text),
  'festivalId' : IDL.Opt(FestivalId),
  'priceGBP' : IDL.Nat,
});
export const PackageId = IDL.Nat;
export const Analytics = IDL.Record({
  'festivalId' : FestivalId,
  'estimatedRevenue' : IDL.Text,
  'estimatedAttendance' : IDL.Nat,
  'ticketsSold' : IDL.Nat,
});
export const Festival = IDL.Record({
  'id' : FestivalId,
  'status' : FestivalStatus,
  'country' : IDL.Text,
  'ticketPriceMax' : IDL.Nat,
  'ticketPriceMin' : IDL.Nat,
  'weekends' : IDL.Text,
  'name' : IDL.Text,
  'ticketUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'season' : Season,
  'ageRestriction' : IDL.Text,
  'company' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'estimatedRevenueMax' : IDL.Text,
  'estimatedRevenueMin' : IDL.Text,
  'location' : IDL.Text,
  'lineup' : IDL.Opt(IDL.Text),
  'specialNotes' : IDL.Opt(IDL.Text),
  'eventType' : EventType,
});
export const Package = IDL.Record({
  'id' : PackageId,
  'packageType' : PackageType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'includes' : IDL.Vec(IDL.Text),
  'festivalId' : IDL.Opt(FestivalId),
  'priceGBP' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addFestival' : IDL.Func([FestivalInput], [FestivalId], []),
  'addPackage' : IDL.Func([PackageInput], [PackageId], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'deleteFestival' : IDL.Func([FestivalId], [IDL.Bool], []),
  'deletePackage' : IDL.Func([PackageId], [IDL.Bool], []),
  'getAnalytics' : IDL.Func([], [IDL.Vec(Analytics)], ['query']),
  'getFestival' : IDL.Func([FestivalId], [IDL.Opt(Festival)], ['query']),
  'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'setFestivalImage' : IDL.Func([FestivalId, IDL.Text], [IDL.Bool], []),
  'setFestivalTicketUrl' : IDL.Func([FestivalId, IDL.Text], [IDL.Bool], []),
  'toggleFestivalStatus' : IDL.Func([FestivalId], [IDL.Bool], []),
  'updateFestival' : IDL.Func([FestivalId, FestivalInput], [IDL.Bool], []),
  'updatePackage' : IDL.Func([PackageId, PackageInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FestivalStatus = IDL.Variant({
    'Active' : IDL.Null,
    'ComingSoon' : IDL.Null,
  });
  const Season = IDL.Variant({ 'Winter' : IDL.Null, 'Summer' : IDL.Null });
  const EventType = IDL.Variant({
    'EDM' : IDL.Null,
    'Family' : IDL.Null,
    'Rave' : IDL.Null,
    'ClubHotel' : IDL.Null,
  });
  const FestivalInput = IDL.Record({
    'status' : FestivalStatus,
    'country' : IDL.Text,
    'ticketPriceMax' : IDL.Nat,
    'ticketPriceMin' : IDL.Nat,
    'weekends' : IDL.Text,
    'name' : IDL.Text,
    'ticketUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'season' : Season,
    'ageRestriction' : IDL.Text,
    'company' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'estimatedRevenueMax' : IDL.Text,
    'estimatedRevenueMin' : IDL.Text,
    'location' : IDL.Text,
    'lineup' : IDL.Opt(IDL.Text),
    'specialNotes' : IDL.Opt(IDL.Text),
    'eventType' : EventType,
  });
  const FestivalId = IDL.Nat;
  const PackageType = IDL.Variant({
    'VIP' : IDL.Null,
    'Weekend1' : IDL.Null,
    'Weekend2' : IDL.Null,
    'FullWeekend' : IDL.Null,
    'Accommodation' : IDL.Null,
    'Transfer' : IDL.Null,
    'FlightPackage' : IDL.Null,
  });
  const PackageInput = IDL.Record({
    'packageType' : PackageType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'includes' : IDL.Vec(IDL.Text),
    'festivalId' : IDL.Opt(FestivalId),
    'priceGBP' : IDL.Nat,
  });
  const PackageId = IDL.Nat;
  const Analytics = IDL.Record({
    'festivalId' : FestivalId,
    'estimatedRevenue' : IDL.Text,
    'estimatedAttendance' : IDL.Nat,
    'ticketsSold' : IDL.Nat,
  });
  const Festival = IDL.Record({
    'id' : FestivalId,
    'status' : FestivalStatus,
    'country' : IDL.Text,
    'ticketPriceMax' : IDL.Nat,
    'ticketPriceMin' : IDL.Nat,
    'weekends' : IDL.Text,
    'name' : IDL.Text,
    'ticketUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'season' : Season,
    'ageRestriction' : IDL.Text,
    'company' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'estimatedRevenueMax' : IDL.Text,
    'estimatedRevenueMin' : IDL.Text,
    'location' : IDL.Text,
    'lineup' : IDL.Opt(IDL.Text),
    'specialNotes' : IDL.Opt(IDL.Text),
    'eventType' : EventType,
  });
  const Package = IDL.Record({
    'id' : PackageId,
    'packageType' : PackageType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'includes' : IDL.Vec(IDL.Text),
    'festivalId' : IDL.Opt(FestivalId),
    'priceGBP' : IDL.Nat,
  });
  
  return IDL.Service({
    'addFestival' : IDL.Func([FestivalInput], [FestivalId], []),
    'addPackage' : IDL.Func([PackageInput], [PackageId], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'deleteFestival' : IDL.Func([FestivalId], [IDL.Bool], []),
    'deletePackage' : IDL.Func([PackageId], [IDL.Bool], []),
    'getAnalytics' : IDL.Func([], [IDL.Vec(Analytics)], ['query']),
    'getFestival' : IDL.Func([FestivalId], [IDL.Opt(Festival)], ['query']),
    'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'setFestivalImage' : IDL.Func([FestivalId, IDL.Text], [IDL.Bool], []),
    'setFestivalTicketUrl' : IDL.Func([FestivalId, IDL.Text], [IDL.Bool], []),
    'toggleFestivalStatus' : IDL.Func([FestivalId], [IDL.Bool], []),
    'updateFestival' : IDL.Func([FestivalId, FestivalInput], [IDL.Bool], []),
    'updatePackage' : IDL.Func([PackageId, PackageInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };