/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'festivalId' : FestivalId,
  'estimatedRevenue' : string,
  'estimatedAttendance' : bigint,
  'ticketsSold' : bigint,
}
export type EventType = { 'EDM' : null } |
  { 'Family' : null } |
  { 'Rave' : null } |
  { 'ClubHotel' : null };
export interface Festival {
  'id' : FestivalId,
  'status' : FestivalStatus,
  'country' : string,
  'ticketPriceMax' : bigint,
  'ticketPriceMin' : bigint,
  'weekends' : string,
  'name' : string,
  'ticketUrl' : [] | [string],
  'description' : [] | [string],
  'season' : Season,
  'ageRestriction' : string,
  'company' : string,
  'imageUrl' : [] | [string],
  'estimatedRevenueMax' : string,
  'estimatedRevenueMin' : string,
  'location' : string,
  'lineup' : [] | [string],
  'specialNotes' : [] | [string],
  'eventType' : EventType,
}
export type FestivalId = bigint;
export interface FestivalInput {
  'status' : FestivalStatus,
  'country' : string,
  'ticketPriceMax' : bigint,
  'ticketPriceMin' : bigint,
  'weekends' : string,
  'name' : string,
  'ticketUrl' : [] | [string],
  'description' : [] | [string],
  'season' : Season,
  'ageRestriction' : string,
  'company' : string,
  'imageUrl' : [] | [string],
  'estimatedRevenueMax' : string,
  'estimatedRevenueMin' : string,
  'location' : string,
  'lineup' : [] | [string],
  'specialNotes' : [] | [string],
  'eventType' : EventType,
}
export type FestivalStatus = { 'Active' : null } |
  { 'ComingSoon' : null };
export interface Package {
  'id' : PackageId,
  'packageType' : PackageType,
  'name' : string,
  'description' : string,
  'includes' : Array<string>,
  'festivalId' : [] | [FestivalId],
  'priceGBP' : bigint,
}
export type PackageId = bigint;
export interface PackageInput {
  'packageType' : PackageType,
  'name' : string,
  'description' : string,
  'includes' : Array<string>,
  'festivalId' : [] | [FestivalId],
  'priceGBP' : bigint,
}
export type PackageType = { 'VIP' : null } |
  { 'Weekend1' : null } |
  { 'Weekend2' : null } |
  { 'FullWeekend' : null } |
  { 'Accommodation' : null } |
  { 'Transfer' : null } |
  { 'FlightPackage' : null };
export type Season = { 'Winter' : null } |
  { 'Summer' : null };
export interface _SERVICE {
  'addFestival' : ActorMethod<[FestivalInput], FestivalId>,
  'addPackage' : ActorMethod<[PackageInput], PackageId>,
  'adminLogin' : ActorMethod<[string], [] | [string]>,
  'deleteFestival' : ActorMethod<[FestivalId], boolean>,
  'deletePackage' : ActorMethod<[PackageId], boolean>,
  'getAnalytics' : ActorMethod<[], Array<Analytics>>,
  'getFestival' : ActorMethod<[FestivalId], [] | [Festival]>,
  'getFestivals' : ActorMethod<[], Array<Festival>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'setFestivalImage' : ActorMethod<[FestivalId, string], boolean>,
  'setFestivalTicketUrl' : ActorMethod<[FestivalId, string], boolean>,
  'toggleFestivalStatus' : ActorMethod<[FestivalId], boolean>,
  'updateFestival' : ActorMethod<[FestivalId, FestivalInput], boolean>,
  'updatePackage' : ActorMethod<[PackageId, PackageInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];