/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type NewsId = bigint;
export interface PackageInput {
    packageType: PackageType;
    name: string;
    description: string;
    includes: Array<string>;
    festivalId?: FestivalId;
    priceGBP: bigint;
}
export type LineupId = bigint;
export interface Festival {
    id: FestivalId;
    status: FestivalStatus;
    country: string;
    ticketPriceMax: bigint;
    ticketPriceMin: bigint;
    weekends: string;
    name: string;
    ticketUrl?: string;
    description?: string;
    season: Season;
    ageRestriction: string;
    company: string;
    imageUrl?: string;
    estimatedRevenueMax: string;
    estimatedRevenueMin: string;
    location: string;
    lineup?: string;
    specialNotes?: string;
    eventType: EventType;
}
export interface Package {
    id: PackageId;
    packageType: PackageType;
    name: string;
    description: string;
    includes: Array<string>;
    festivalId?: FestivalId;
    priceGBP: bigint;
}
export interface LineupEntry {
    id: LineupId;
    stage: string;
    festivalId: FestivalId;
    artistName: string;
    timeSlot: string;
}
export interface Analytics {
    festivalId: FestivalId;
    estimatedRevenue: string;
    estimatedAttendance: bigint;
    ticketsSold: bigint;
}
export interface FestivalInput {
    status: FestivalStatus;
    country: string;
    ticketPriceMax: bigint;
    ticketPriceMin: bigint;
    weekends: string;
    name: string;
    ticketUrl?: string;
    description?: string;
    season: Season;
    ageRestriction: string;
    company: string;
    imageUrl?: string;
    estimatedRevenueMax: string;
    estimatedRevenueMin: string;
    location: string;
    lineup?: string;
    specialNotes?: string;
    eventType: EventType;
}
export type PackageId = bigint;
export interface NewsArticle {
    id: NewsId;
    title: string;
    content: string;
    publishDate: Timestamp;
    createdAt: Timestamp;
    imageUrl: string;
}
export type FestivalId = bigint;
export interface NewsInput {
    title: string;
    content: string;
    publishDate: Timestamp;
    imageUrl: string;
}
export interface LineupInput {
    stage: string;
    festivalId: FestivalId;
    artistName: string;
    timeSlot: string;
}
export enum EventType {
    EDM = "EDM",
    Family = "Family",
    Rave = "Rave",
    ClubHotel = "ClubHotel"
}
export enum FestivalStatus {
    Active = "Active",
    ComingSoon = "ComingSoon"
}
export enum PackageType {
    VIP = "VIP",
    Weekend1 = "Weekend1",
    Weekend2 = "Weekend2",
    FullWeekend = "FullWeekend",
    Accommodation = "Accommodation",
    Transfer = "Transfer",
    FlightPackage = "FlightPackage"
}
export enum Season {
    Winter = "Winter",
    Summer = "Summer"
}
export interface backendInterface {
    addFestival(input: FestivalInput): Promise<FestivalId>;
    addLineupEntry(input: LineupInput): Promise<LineupId>;
    addNews(input: NewsInput): Promise<NewsId>;
    addPackage(input: PackageInput): Promise<PackageId>;
    adminLogin(password: string): Promise<string | null>;
    deleteFestival(id: FestivalId): Promise<boolean>;
    deleteLineupEntry(id: LineupId): Promise<boolean>;
    deleteNews(id: NewsId): Promise<boolean>;
    deletePackage(id: PackageId): Promise<boolean>;
    getAnalytics(): Promise<Array<Analytics>>;
    getFestival(id: FestivalId): Promise<Festival | null>;
    getFestivals(): Promise<Array<Festival>>;
    getLineup(festivalId: FestivalId): Promise<Array<LineupEntry>>;
    getNews(): Promise<Array<NewsArticle>>;
    getNewsArticle(id: NewsId): Promise<NewsArticle | null>;
    getPackages(): Promise<Array<Package>>;
    setFestivalImage(id: FestivalId, imageUrl: string): Promise<boolean>;
    setFestivalTicketUrl(id: FestivalId, url: string): Promise<boolean>;
    toggleFestivalStatus(id: FestivalId): Promise<boolean>;
    updateFestival(id: FestivalId, input: FestivalInput): Promise<boolean>;
    updateLineupEntry(id: LineupId, input: LineupInput): Promise<boolean>;
    updateNews(id: NewsId, input: NewsInput): Promise<boolean>;
    updatePackage(id: PackageId, input: PackageInput): Promise<boolean>;
}
import type { EventType as _EventType, Festival as _Festival, FestivalId as _FestivalId, FestivalInput as _FestivalInput, FestivalStatus as _FestivalStatus, NewsArticle as _NewsArticle, Package as _Package, PackageId as _PackageId, PackageInput as _PackageInput, PackageType as _PackageType, Season as _Season } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFestival(arg0: FestivalInput): Promise<FestivalId> {
        if (this.processError) {
            try {
                const result = await this.actor.addFestival(to_candid_FestivalInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFestival(to_candid_FestivalInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLineupEntry(arg0: LineupInput): Promise<LineupId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLineupEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLineupEntry(arg0);
            return result;
        }
    }
    async addNews(arg0: NewsInput): Promise<NewsId> {
        if (this.processError) {
            try {
                const result = await this.actor.addNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNews(arg0);
            return result;
        }
    }
    async addPackage(arg0: PackageInput): Promise<PackageId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackage(to_candid_PackageInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackage(to_candid_PackageInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFestival(arg0: FestivalId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFestival(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFestival(arg0);
            return result;
        }
    }
    async deleteLineupEntry(arg0: LineupId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLineupEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLineupEntry(arg0);
            return result;
        }
    }
    async deleteNews(arg0: NewsId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async deletePackage(arg0: PackageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<Array<Analytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getFestival(arg0: FestivalId): Promise<Festival | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFestival(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFestival(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFestivals(): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFestivals();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFestivals();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLineup(arg0: FestivalId): Promise<Array<LineupEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLineup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLineup(arg0);
            return result;
        }
    }
    async getNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews();
            return result;
        }
    }
    async getNewsArticle(arg0: NewsId): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticle(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticle(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFestivalImage(arg0: FestivalId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFestivalImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFestivalImage(arg0, arg1);
            return result;
        }
    }
    async setFestivalTicketUrl(arg0: FestivalId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFestivalTicketUrl(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFestivalTicketUrl(arg0, arg1);
            return result;
        }
    }
    async toggleFestivalStatus(arg0: FestivalId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFestivalStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFestivalStatus(arg0);
            return result;
        }
    }
    async updateFestival(arg0: FestivalId, arg1: FestivalInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFestival(arg0, to_candid_FestivalInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFestival(arg0, to_candid_FestivalInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLineupEntry(arg0: LineupId, arg1: LineupInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLineupEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLineupEntry(arg0, arg1);
            return result;
        }
    }
    async updateNews(arg0: NewsId, arg1: NewsInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(arg0, arg1);
            return result;
        }
    }
    async updatePackage(arg0: PackageId, arg1: PackageInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, to_candid_PackageInput_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, to_candid_PackageInput_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EventType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_FestivalStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FestivalStatus): FestivalStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Festival_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Festival): Festival {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PackageType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackageType): PackageType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Package_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Package): Package {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Season_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Season): Season {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Festival]): Festival | null {
    return value.length === 0 ? null : from_candid_Festival_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): NewsArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FestivalId]): FestivalId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FestivalId;
    status: _FestivalStatus;
    country: string;
    ticketPriceMax: bigint;
    ticketPriceMin: bigint;
    weekends: string;
    name: string;
    ticketUrl: [] | [string];
    description: [] | [string];
    season: _Season;
    ageRestriction: string;
    company: string;
    imageUrl: [] | [string];
    estimatedRevenueMax: string;
    estimatedRevenueMin: string;
    location: string;
    lineup: [] | [string];
    specialNotes: [] | [string];
    eventType: _EventType;
}): {
    id: FestivalId;
    status: FestivalStatus;
    country: string;
    ticketPriceMax: bigint;
    ticketPriceMin: bigint;
    weekends: string;
    name: string;
    ticketUrl?: string;
    description?: string;
    season: Season;
    ageRestriction: string;
    company: string;
    imageUrl?: string;
    estimatedRevenueMax: string;
    estimatedRevenueMin: string;
    location: string;
    lineup?: string;
    specialNotes?: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        status: from_candid_FestivalStatus_n17(_uploadFile, _downloadFile, value.status),
        country: value.country,
        ticketPriceMax: value.ticketPriceMax,
        ticketPriceMin: value.ticketPriceMin,
        weekends: value.weekends,
        name: value.name,
        ticketUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.ticketUrl)),
        description: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.description)),
        season: from_candid_Season_n19(_uploadFile, _downloadFile, value.season),
        ageRestriction: value.ageRestriction,
        company: value.company,
        imageUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.imageUrl)),
        estimatedRevenueMax: value.estimatedRevenueMax,
        estimatedRevenueMin: value.estimatedRevenueMin,
        location: value.location,
        lineup: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lineup)),
        specialNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.specialNotes)),
        eventType: from_candid_EventType_n21(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PackageId;
    packageType: _PackageType;
    name: string;
    description: string;
    includes: Array<string>;
    festivalId: [] | [_FestivalId];
    priceGBP: bigint;
}): {
    id: PackageId;
    packageType: PackageType;
    name: string;
    description: string;
    includes: Array<string>;
    festivalId?: FestivalId;
    priceGBP: bigint;
} {
    return {
        id: value.id,
        packageType: from_candid_PackageType_n28(_uploadFile, _downloadFile, value.packageType),
        name: value.name,
        description: value.description,
        includes: value.includes,
        festivalId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.festivalId)),
        priceGBP: value.priceGBP
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    ComingSoon: null;
}): FestivalStatus {
    return "Active" in value ? FestivalStatus.Active : "ComingSoon" in value ? FestivalStatus.ComingSoon : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Winter: null;
} | {
    Summer: null;
}): Season {
    return "Winter" in value ? Season.Winter : "Summer" in value ? Season.Summer : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EDM: null;
} | {
    Family: null;
} | {
    Rave: null;
} | {
    ClubHotel: null;
}): EventType {
    return "EDM" in value ? EventType.EDM : "Family" in value ? EventType.Family : "Rave" in value ? EventType.Rave : "ClubHotel" in value ? EventType.ClubHotel : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VIP: null;
} | {
    Weekend1: null;
} | {
    Weekend2: null;
} | {
    FullWeekend: null;
} | {
    Accommodation: null;
} | {
    Transfer: null;
} | {
    FlightPackage: null;
}): PackageType {
    return "VIP" in value ? PackageType.VIP : "Weekend1" in value ? PackageType.Weekend1 : "Weekend2" in value ? PackageType.Weekend2 : "FullWeekend" in value ? PackageType.FullWeekend : "Accommodation" in value ? PackageType.Accommodation : "Transfer" in value ? PackageType.Transfer : "FlightPackage" in value ? PackageType.FlightPackage : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Festival>): Array<Festival> {
    return value.map((x)=>from_candid_Festival_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Package>): Array<Package> {
    return value.map((x)=>from_candid_Package_n26(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_FestivalInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FestivalInput): _FestivalInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FestivalStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FestivalStatus): _FestivalStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PackageInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageInput): _PackageInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PackageType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageType): _PackageType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Season_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Season): _Season {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packageType: PackageType;
    name: string;
    description: string;
    includes: Array<string>;
    festivalId?: FestivalId;
    priceGBP: bigint;
}): {
    packageType: _PackageType;
    name: string;
    description: string;
    includes: Array<string>;
    festivalId: [] | [_FestivalId];
    priceGBP: bigint;
} {
    return {
        packageType: to_candid_PackageType_n11(_uploadFile, _downloadFile, value.packageType),
        name: value.name,
        description: value.description,
        includes: value.includes,
        festivalId: value.festivalId ? candid_some(value.festivalId) : candid_none(),
        priceGBP: value.priceGBP
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: FestivalStatus;
    country: string;
    ticketPriceMax: bigint;
    ticketPriceMin: bigint;
    weekends: string;
    name: string;
    ticketUrl?: string;
    description?: string;
    season: Season;
    ageRestriction: string;
    company: string;
    imageUrl?: string;
    estimatedRevenueMax: string;
    estimatedRevenueMin: string;
    location: string;
    lineup?: string;
    specialNotes?: string;
    eventType: EventType;
}): {
    status: _FestivalStatus;
    country: string;
    ticketPriceMax: bigint;
    ticketPriceMin: bigint;
    weekends: string;
    name: string;
    ticketUrl: [] | [string];
    description: [] | [string];
    season: _Season;
    ageRestriction: string;
    company: string;
    imageUrl: [] | [string];
    estimatedRevenueMax: string;
    estimatedRevenueMin: string;
    location: string;
    lineup: [] | [string];
    specialNotes: [] | [string];
    eventType: _EventType;
} {
    return {
        status: to_candid_FestivalStatus_n3(_uploadFile, _downloadFile, value.status),
        country: value.country,
        ticketPriceMax: value.ticketPriceMax,
        ticketPriceMin: value.ticketPriceMin,
        weekends: value.weekends,
        name: value.name,
        ticketUrl: value.ticketUrl ? candid_some(value.ticketUrl) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        season: to_candid_Season_n5(_uploadFile, _downloadFile, value.season),
        ageRestriction: value.ageRestriction,
        company: value.company,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        estimatedRevenueMax: value.estimatedRevenueMax,
        estimatedRevenueMin: value.estimatedRevenueMin,
        location: value.location,
        lineup: value.lineup ? candid_some(value.lineup) : candid_none(),
        specialNotes: value.specialNotes ? candid_some(value.specialNotes) : candid_none(),
        eventType: to_candid_EventType_n7(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageType): {
    VIP: null;
} | {
    Weekend1: null;
} | {
    Weekend2: null;
} | {
    FullWeekend: null;
} | {
    Accommodation: null;
} | {
    Transfer: null;
} | {
    FlightPackage: null;
} {
    return value == PackageType.VIP ? {
        VIP: null
    } : value == PackageType.Weekend1 ? {
        Weekend1: null
    } : value == PackageType.Weekend2 ? {
        Weekend2: null
    } : value == PackageType.FullWeekend ? {
        FullWeekend: null
    } : value == PackageType.Accommodation ? {
        Accommodation: null
    } : value == PackageType.Transfer ? {
        Transfer: null
    } : value == PackageType.FlightPackage ? {
        FlightPackage: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FestivalStatus): {
    Active: null;
} | {
    ComingSoon: null;
} {
    return value == FestivalStatus.Active ? {
        Active: null
    } : value == FestivalStatus.ComingSoon ? {
        ComingSoon: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Season): {
    Winter: null;
} | {
    Summer: null;
} {
    return value == Season.Winter ? {
        Winter: null
    } : value == Season.Summer ? {
        Summer: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    EDM: null;
} | {
    Family: null;
} | {
    Rave: null;
} | {
    ClubHotel: null;
} {
    return value == EventType.EDM ? {
        EDM: null
    } : value == EventType.Family ? {
        Family: null
    } : value == EventType.Rave ? {
        Rave: null
    } : value == EventType.ClubHotel ? {
        ClubHotel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
